# -*- coding: utf-8 -*-
"""Hands-on Activity 7.2 Webscraping using BeautifulSoup and Requests | DANO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Quv_ud0LcNFoFh4RS31kLE7ubhnd7t6v

Data Gathering <br>
Sources of Data<br>
A vast amount of historical data can be found in files such as:
* MS Word documents
* Emails
* Spreadsheets
* MS PowerPoints
* PDFs
* HTML
* and plaintext files

Public and Private Archives
CSV, JSON, and XML files use plaintext, a common format, and are compatible with a wide range of applications
The Web can be mined for data using a web scraping application
The IoT uses sensors create data
Sensors in smartphones, cars, airplanes, street lamps, and home appliances capture raw data
Open Data and Private Data
1. Open Data
The Open Knowledge Foundation describes Open Data as “any content, information or data that people are free to use, reuse, and redistribute without any legal,
technological, or social restriction.”
1. Private Data
Data related to an expectation of privacy and regulated by a particular country/government
Structured and Unstructured Data
1. Structured Data
Data entered and maintained in fixed fields within a file or record Easily entered, classified, queried, and analyzed Relational databases or spreadsheets
2. Unstructured Data Lacks organization
Raw data Photo contents, audio, video, web pages, blogs, books, journals, white papers, PowerPoint presentations, articles, email, wikis, word processing
documents, and text in general
Example of gathering image data using webcam
Note: Run this snippet using local jupyter notebook
"""

import cv2

# Open webcam
webcam = cv2.VideoCapture(0)

while True:
    check, frame = webcam.read()
    if not check:
        print("Camera not detected.")
        break

    cv2.imshow("Capturing", frame)

    key = cv2.waitKey(1)

    # Press 's' to save image
    if key == ord('s'):
        cv2.imwrite("saved_img.jpg", frame)
        print("Image saved!")

        # Convert to grayscale
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        # Resize to 28x28
        resized = cv2.resize(gray, (28, 28))

        cv2.imwrite("saved_img_final.jpg", resized)
        print("Grayscale 28x28 image saved!")
        break

    # Press 'q' to quit
    elif key == ord('q'):
        print("Camera turned off.")
        break

webcam.release()
cv2.destroyAllWindows()

"""Example of gathering voice data using microphone
Note: Run the snippet of codes using local jupyter notebook
"""

!pip install sounddevice scipy wavio
!pip3 install wavio
!pip3 install scipy
!apt-get install libportaudio2

import sounddevice as sd
from scipy.io.wavfile import write
import wavio as wv

# Sampling frequency
freq = 44100

# Duration (seconds)
duration = 5

print("Recording...")

# Record
recording = sd.rec(int(duration * freq),
                   samplerate=freq,
                   channels=2)

sd.wait()
print("Recording finished!")

# Save file
write("recording.wav", freq, recording)

# Optional save using wavio
wv.write("recording_wavio.wav", recording, freq, sampwidth=2)

print("Audio saved successfully!")

pip install requests bs4

import requests
from bs4 import BeautifulSoup

def getdata(url):
    response = requests.get(url)
    return response.text

url = "https://www.google.com/"
htmldata = getdata(url)

soup = BeautifulSoup(htmldata, 'html.parser')

# Print image sources
for img in soup.find_all('img'):
    print(img.get('src'))

from requests import get
from bs4 import BeautifulSoup
import pandas as pd

headers = {'Accept-Language': 'en-US,en;q=0.8'}

url = 'https://www.imdb.com/search/title?release_date=2017&sort=num_votes,desc&page=1'
response = get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')
movie_containers = soup.find_all('div', class_='lister-item mode-advanced')

names = []
years = []
imdb_ratings = []
metascores = []
votes = []

for container in movie_containers:
    if container.find('div', class_='ratings-metascore') is not None:

        name = container.h3.a.text
        names.append(name)

        year = container.h3.find('span', class_='lister-item-year').text
        years.append(year)

        imdb = float(container.strong.text)
        imdb_ratings.append(imdb)

        m_score = container.find('span', class_='metascore').text.strip()
        metascores.append(int(m_score))

        vote = container.find('span', attrs={'name': 'nv'})['data-value']
        votes.append(int(vote))

df = pd.DataFrame({
    'movie': names,
    'year': years,
    'imdb': imdb_ratings,
    'metascore': metascores,
    'votes': votes
})

print(df.head())

df['year'] = df['year'].astype(str)

df['year'] = df['year'].str.replace('(I)', '', regex=False)
df['year'] = df['year'].str.replace('(II)', '', regex=False)
df['year'] = df['year'].str.replace('(III)', '', regex=False)

df['year'] = df['year'].str.replace('(', '', regex=False)
df['year'] = df['year'].str.replace(')', '', regex=False)

# Remove extra spaces (important)
df['year'] = df['year'].str.strip()

# Convert to integer
df['year'] = df['year'].astype(int)

print(df.dtypes)

df.to_csv("movie_ratings.csv", index=False)
print("CSV file saved successfully!")

"""MULTIPLE PAGE SCRAPING (IMDB)"""

from time import sleep
from random import randint

pages = ['1','2','3','4','5']
years_list = ['2017','2018','2019','2020']

names = []
years = []
imdb_ratings = []
metascores = []
votes = []

for year in years_list:
    for page in pages:

        url = f"https://www.imdb.com/search/title?release_date={year}&sort=num_votes,desc&page={page}"
        response = get(url, headers=headers)
        sleep(randint(8,12))

        soup = BeautifulSoup(response.text, "html.parser")
        containers = soup.find_all('div', class_='lister-item mode-advanced')

        for container in containers:
            if container.find('div', class_='ratings-metascore'):

                names.append(container.h3.a.text)
                years.append(container.h3.find('span', class_='lister-item-year').text)
                imdb_ratings.append(float(container.strong.text))
                metascores.append(int(container.find('span', class_='metascore').text.strip()))
                votes.append(int(container.find('span', attrs={'name':'nv'})['data-value']))

movie_ratings = pd.DataFrame({
    'movie': names,
    'year': years,
    'imdb': imdb_ratings,
    'metascore': metascores,
    'votes': votes
})

print(movie_ratings.info())

"""Conclusion:

The activity demonstrated how data can be gathered from multiple sources such as documents, sensors, the web, and online databases. It highlighted the importance of understanding different data types, structured and unstructured,  and how it is processed before analysis. With the power of web scraping, image capture, and data cleaning using Python libraries, the process of transforming raw data into meaningful information became clearer. Overall, data gathering is not just about collecting information, but about preparing it properly for analysis and decision-making.
"""